// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/template.tsx";
import * as $$0 from "./islands/Output.tsx";

const manifest = {
  routes: {
    "./routes/template.tsx": $0,
  },
  islands: {
    "./islands/Output.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
