// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/template.tsx";
import * as $$0 from "./islands/GameLink.tsx";
import * as $$1 from "./islands/Output.tsx";
import * as $$2 from "./islands/RunButton.tsx";
import * as $$3 from "./islands/TinyPepper.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/template.tsx": $1,
  },
  islands: {
    "./islands/GameLink.tsx": $$0,
    "./islands/Output.tsx": $$1,
    "./islands/RunButton.tsx": $$2,
    "./islands/TinyPepper.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
